### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Tacodiva** [Tacodiva/Scuff#1]
*The text based list was getting unmaintainable, so I've decided to move it here.*

# Big ol' List of Todos

Once everything on this list is completed, the editor should be in a usable state. This list is not complete and I'll add stuff as I think of it. Bold tasks are ones that might take a long time, italic tasks aren't necessary but I want to do them anyways..

### Block Renderer (Scuffr)
- [ ] _Fix nested block spacing_
- [ ] Make tab move to the next input
- [X] **Add block palette sidebar (with a good API)**
- [ ] Make proper API for the SVG definitions
- [ ] Comments
- [ ] Make the right click menu items actually do stuff
- [ ] Add global drag and drop
- [ ] Make script order reliable + add hat block priority in context menu
- [ ] Scrolling while dragging blocks
- [ ] **Custom block editor**

### Editor
- [ ] _Ability to grab corners of windows_
- [x] Constrain split pane size
- [ ] VSCode-like Tabs
- [x] Move interaction management from `ScuffrWorkspace` to `ScuffEditor`.
- [x] Move context menu to editor
- [ ] Menu bar
- [ ] Hotkey system

### Core
- [ ] **Use a component system for block properties + move Scuffr stuff into components**
- [x] Add targets properly
- [ ] L10N
- [x] _Add Monaco editor window_
- [ ] **Saving and loading projects to custom format**
- [ ] Reorganize CSS

### Scratch
- [ ] Add scratch-paint as an editor window
- [ ] Custom block support
- [ ] Add the sound editor as an editor window **?**
- [ ] Create target list and inspector editor windows.
- [ ] **Importing and exporting as SB3.**

### Scratch Runtime
- [X] Create Scratch Runtime ~~(a fork of scratch-vm, bundled inside scuff-scratch)~~
- [X] Bundle scratch-render, scratch-audio and scratch-svg-renderer  and create an editor window for the actual project.
- [ ] **Program the whole engine lmao.**
- [X] Sandbox compiled code execution in an iframe.
- [ ] **Move all compiler and block logic into components**

**Comment by nexensys** [comment]
Suggestion:

### Editor

- [ ] Global clipboard. Use either the clipboard API or the `copy` function to allow copy-and-paste between browser tabs, not just editor tabs.
